# Generated by Django 4.1.1 on 2022-12-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='car',
            field=models.ImageField(default='images/DS.jpeg', upload_to='pics'),
        ),
    ]
